training:
  batch_size: 8
  n_epochs: 500000
  n_iters: 500001
  ngpu: 1
  snapshot_freq: 5000
  algo: 'dsm'
  anneal_power: 2.0

data:
  dataset: "Bedroom"
  image_size: 64
  channels: 12
  logit_transform: false
  random_flip: true

#  dataset: "Church"
#  image_size: 64
#  channels: 12
#  logit_transform: false
#  random_flip: true

#  dataset: "Coco"
#  image_size: 64
#  channels: 12
#  logit_transform: false
#  random_flip: true

model:
  sigma_begin: 1
  sigma_end: 0.01
  num_classes: 10
  batch_norm: false
  ngf: 128

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: false
